routes:
    - route: "^.+\\.(js|css|svg|ttf)$"
      #  cache static assets for 30 days
      headers:
         Cache-Control: "max-age=2592000, no-transform, public"
      gzip: true
    - route: "^.+\\.(png|jpg)$"
      headers:
         Cache-Control: "max-age=2592000, no-transform, public"
      gzip: false
    - route: "^.+\\.(html|xml|json)$"
      gzip: true