baseURL = "https://www.michaelgrosser.com/"
languageCode = "en-us"
title = "Michael Grosser"
theme = "minimal"
googleAnalytics = "UA-12875860-1"

[params]
    author = "Michael Grosser"
    description = ""
    githubUsername = "michaelgrosser"
    accent = "#cccccc"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "kotlin", "java", "swift", "php", "python", "javascript"]
    profilePic = "/img/mg.jpg"
[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about"
    name = "About"
    weight = 2

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:michaelgrosser@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/michaelgrosser/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/michaelgrosser/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.instagram.com/michaelinchicago/"
    name = "instagram"
    weight = 4

[[menu.icon]]
    url = "https://www.linkedin.com/in/michaelgrosser/"
    name = "linkedin"
    weight = 5